import json
from pathlib import Path
from jinja2 import Template
from pipeline.utils.logger import setup_logger

logger = setup_logger(__name__)

HTML_TEMPLATE = """
<html>
<head>
    <title>NGS Pipeline Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        .header { background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }
        .section { margin: 20px 0; padding: 15px; border: 1px solid #ddd; background: white; border-radius: 5px; }
        h1 { color: #333; }
        h2 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        table { border-collapse: collapse; width: 100%; margin: 10px 0; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #3498db; color: white; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .success { color: green; font-weight: bold; }
        .warning { color: orange; font-weight: bold; }
        .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🧬 NGS Pipeline Analysis Report</h1>
        <p>End-to-end bioinformatics pipeline results</p>
    </div>
    
    <div class="section">
        <h2>Summary Statistics</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th>Value</th>
            </tr>
            {% for key, value in summary.items() %}
            <tr>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    
    <div class="section">
        <h2>Quality Control</h2>
        <pre>{{ qc_data }}</pre>
    </div>
    
    {% if annotation_data %}
    <div class="section">
        <h2>Variant Annotations</h2>
        <p>Top annotated variants:</p>
        <table>
            <tr>
                <th>Chr</th>
                <th>Position</th>
                <th>Ref</th>
                <th>Alt</th>
                <th>Quality</th>
            </tr>
            {% for variant in annotation_data[:10] %}
            <tr>
                <td>{{ variant.chromosome }}</td>
                <td>{{ variant.position }}</td>
                <td>{{ variant.ref }}</td>
                <td>{{ variant.alt }}</td>
                <td>{{ variant.quality }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endif %}
    
    <div class="section">
        <h2 class="success">✅ Analysis Complete</h2>
        <p>All pipeline stages completed successfully.</p>
    </div>
    
    <div class="footer">
        <p>Generated by NGS Data Processing Pipeline v0.2.0</p>
        <p>Built for bioinformatics research | MIT License</p>
    </div>
</body>
</html>
"""

def generate_html_report(output_dir, qc_stats, variant_count, annotation_data=None):
    """Generate HTML report"""
    logger.info(f"Generating HTML report...")
    
    template = Template(HTML_TEMPLATE)
    
    summary = {
        'Total Reads': qc_stats.get('reads', 'N/A'),
        'Total Bases': qc_stats.get('total_bases', 'N/A'),
        'Avg Quality': qc_stats.get('avg_quality', 'N/A'),
        'Variants Called': variant_count,
        'Variants Annotated': len(annotation_data) if annotation_data else 'N/A',
    }
    
    html_content = template.render(
        summary=summary,
        qc_data=json.dumps(qc_stats, indent=2),
        annotation_data=annotation_data or []
    )
    
    report_path = Path(output_dir) / 'report.html'
    with open(report_path, 'w') as f:
        f.write(html_content)
    
    logger.info(f"✅ Report generated: {report_path}")
    return report_path
